// PATTERN

const offers = {
  // last update hairstyles list date
  date: "03.08.2020",
  offersWoman: [
    {
      id: 0,
      img: "k1_1.jpg",
      gallery: ["k1_2.jpg", "k1_3.jpg", "k1_4.jpg", "k1_5"],
      tags: ["short", "woman", "wedding", "hair"],
      price: 10,
    },
    {
      id: 1,
      img: "k2_1.jpg",
      gallery: ["k2_2.jpg", "k2_3.jpg", "k2_4.jpg"],
      tags: ["long", "woman", "highlights", "hair"],
      price: 10,
    },
    {
      id: 2,
      img: "k3_1.jpg",
      gallery: ["k3_2.jpg", "k3_3.jpg", "k3_4.jpg"],
      tags: ["medium", "woman", "highlights", "hair"],
      price: 10,
    },
    {
      id: 3,
      img: "k4_1.jpg",
      gallery: ["k4_2.jpg", "k4_3.jpg", "k4_4.jpg"],
      tags: ["long", "woman", "hair"],
      price: 10,
    },
    {
      id: 4,
      img: "k5_1.jpg",
      gallery: ["k5_1.jpg", "k5_3.jpg", "k5_4.jpg"],
      tags: ["long", "woman", "side fringe", "hair"],
      price: 10,
    },
    {
      id: 5,
      img: "k6_1.jpg",
      gallery: ["k6_2.jpg", "k6_3.jpg", "k6_4.jpg"],
      tags: ["curly", "short", "woman", "hair"],
      price: 10,
    },
    {
      id: 6,
      img: "k7_1.jpg",
      gallery: ["k7_2.jpg", "k7_3.jpg", "k7_4.jpg"],
      tags: ["braid", "long", "woman", "hair"],
      price: 10,
    },
    {
      id: 7,
      img: "k8_1.jpg",
      gallery: ["k8_2.jpg", "k8_3.jpg", "k8_4.jpg", "k8_5.jpg"],
      tags: ["ponytail", "long", "woman", "hair"],
      price: 10,
    },
    {
      id: 8,
      img: "k9_1.jpg",
      gallery: ["k9_2.jpg", "k9_3.jpg", "k9_4.jpg", "k9_5.jpg"],
      tags: ["straight", "long", "woman", "hair"],
      price: 10,
    },
    {
      id: 9,
      img: "k10_1.jpg",
      gallery: ["k10_2.jpg", "k10_3.jpg", "k10_4.jpg", "k10_5.jpg"],
      tags: ["ponytails", "long", "woman", "junko", "hair"],
      price: 10,
    },
    {
      id: 10,
      img: "k11_1.jpg",
      gallery: [
        "k11_2.jpg",
        "k11_3.jpg",
        "k11_4.jpg",
        "k11_5.jpg",
        "k11_6.jpg",
      ],
      tags: ["wavy", "short", "woman", "cute", "hair"],
      price: 15,
    },
    {
      id: 11,
      img: "k12_1.jpg",
      gallery: [
        "k12_2.jpg",
        "k12_3.jpg",
        "k12_4.jpg",
        "k12_5.jpg",
        "k12_6.jpg",
      ],
      tags: ["ponytail", "long", "woman", "hair"],
      price: 10,
    },
    {
      id: 12,
      img: "k13_1.jpg",
      gallery: ["k13_5.jpg", "k13_2.jpg", "k13_3.jpg", "k13_4.jpg"],
      tags: ["princess", "woman", "hair", "long", "pinned"],
      price: 15,
    },
    {
      id: 13,
      img: "k14_1.jpg",
      gallery: ["k14_5.jpg", "k14_2.jpg", "k14_3.jpg", "k14_4.jpg"],
      tags: ["short", "woman", "hair", "princess", "cute", "pinned"],
      price: 15,
    },
    // {
    //   id: 14,
    //   img: "k14_1.jpg",
    //   gallery: ["k14_5.jpg", "k14_2.jpg", "k14_3.jpg", "k14_4.jpg"],
    //   tags: ["short", "woman", "hair", "princess", "cute", "pinned"],
    //   price: 1,
    // },
  ],
  offersMan: [
    {
      id: 100,
      img: "m1_1.jpg",
      gallery: ["m1_2.jpg", "m1_3.jpg", "m1_4.jpg", "m1_5.jpg"],
      tags: ["short", "man", "hair"],
      price: 10,
    },
    {
      id: 101,
      img: "m2_1.jpg",
      gallery: ["m2_2.jpg", "m2_3.jpg", "m2_4.jpg", "m2_5.jpg"],
      tags: ["short", "man", "hair"],
      price: 10,
    },
    {
      id: 102,
      img: "m3_1.jpg",
      gallery: ["m3_2.jpg", "m3_3.jpg", "m3_4.jpg", "m3_5.jpg"],
      tags: ["short", "man", "hair"],
      price: 10,
    },
    {
      id: 103,
      img: "m4_1.jpg",
      gallery: ["m4_2.jpg", "m4_3.jpg", "m4_4.jpg", "m4_5.jpg", "m4_6.jpg"],
      tags: ["short", "pony", "man", "hair"],
      price: 10,
    },
    {
      id: 104,
      img: "m5_1.jpg",
      gallery: ["m5_2.jpg", "m5_3.jpg", "m5_4.jpg", "m5_5.jpg", "m5_6.jpg"],
      tags: ["short", "man", "hair"],
      price: 10,
    },
    {
      id: 105,
      img: "m6_1.jpg",
      gallery: ["m6_2.jpg", "m6_3.jpg", "m6_4.jpg", "m6_5.jpg"],
      tags: ["short", "man", "hair"],
      price: 10,
    },
    {
      id: 106,
      img: "m7_1.jpg",
      gallery: ["m7_2.jpg", "m7_3.jpg", "m7_4.jpg", "m7_5.jpg"],
      tags: ["justin", "short", "man", "hair"],
      price: 10,
    },
    {
      id: 107,
      img: "m8_1.jpg",
      gallery: ["m8_2.jpg", "m8_3.jpg", "m8_4.jpg", "m8_5.jpg"],
      tags: ["short", "man", "japan", "hair"],
      price: 10,
    },
    {
      id: 108,
      img: "m9_1.jpg",
      gallery: ["m9_2.jpg", "m9_3.jpg", "m9_4.jpg", "m9_5.jpg"],
      tags: ["short", "man", "dreads", "hair"],
      price: 10,
    },
  ],
}

export default offers
