export const ADD_ORDER = "ADD_ORDER"
export const REMOVE_ORDER = "REMOVE_ORDER"
export const SEARCH = "SEARCH"
export const ADD_TO_SEARCH = "ADD_TO_SEARCH"
export const REMOVE_FROM_SEARCH = "REMOVE_FROM_SEARCH"
